### ISSUE TITLE
socket issue

### ISSUE THREAD

**Issue by ook** [LapoElisacci/Ksql#16]
Hi,

I'm trying this gem, I'm having issue while setup the gem. My kafka and ksql are hosted into a docker-compose environment.
No problem when using `curl`:

```
Ksql [main] ⚡ curl -sX GET "http://ksql:8088/info" | jq '.'
{
  "KsqlServerInfo": {
    "version": "5.4.7",
    "kafkaClusterId": "8iRkPI5kQOWciOGXzvbPYw",
    "ksqlServiceId": "default_"
  }
}
```

But in rails console (ruby 3.1.1):
```
[1] pry(main)> Ksql.config
=> Ksql::Configuration {
  :host => nil
}
[2] pry(main)> Ksql.configure {|c| c.host = 'http://ksql:8088'}
=> "http://ksql:8088"
[3] pry(main)> Ksql.config
=> Ksql::Configuration {
  :host => "http://ksql:8088"
}
[4] pry(main)> Ksql::Client.info
#<Thread:0x00007fa094dfc410 /usr/local/bundle/gems/net-http2-0.18.4/lib/net-http2/client.rb:112 run> terminated with exception (report_on_exception is true):
/usr/local/bundle/gems/net-http2-0.18.4/lib/net-http2/client.rb:134:in `callback_or_raise': Socket was remotely closed (SocketError)
	from /usr/local/bundle/gems/net-http2-0.18.4/lib/net-http2/client.rb:119:in `rescue in block (2 levels) in ensure_open'
	from /usr/local/bundle/gems/net-http2-0.18.4/lib/net-http2/client.rb:113:in `block (2 levels) in ensure_open'
/usr/local/lib/ruby/3.0.0/socket.rb:452:in `__read_nonblock': end of file reached (EOFError)
	from /usr/local/lib/ruby/3.0.0/socket.rb:452:in `read_nonblock'
	from /usr/local/bundle/gems/net-http2-0.18.4/lib/net-http2/client.rb:145:in `block in socket_loop'
	from /usr/local/bundle/gems/net-http2-0.18.4/lib/net-http2/client.rb:142:in `loop'
	from /usr/local/bundle/gems/net-http2-0.18.4/lib/net-http2/client.rb:142:in `socket_loop'
	from /usr/local/bundle/gems/net-http2-0.18.4/lib/net-http2/client.rb:114:in `block (2 levels) in ensure_open'
SocketError: Socket was remotely closed
from /usr/local/bundle/gems/net-http2-0.18.4/lib/net-http2/client.rb:134:in `callback_or_raise'
Caused by EOFError: end of file reached
from /usr/local/lib/ruby/3.0.0/socket.rb:452:in `__read_nonblock'
```

Could you advise where should I look to fix that?
Thank you.

**Comment by LapoElisacci** [comment]
Hi @ook, thanks for your feedback.

By looking at the stack trace, it seems like the host is refusing the connection from the Client, I've quickly tested the client under Ruby 3.1.1 and I'm not facing any issue.

Also, I don't quite get how's it possible that your `KsqlServerInfo` version says "5.4.7", when the latest release of ksqlDB is `0.25.1`.

Please, make sure your local environment is properly set up.
Here's a Docker Compose file you can start working with:

```YAML
---
version: '2'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  ksqldb-server:
    image: confluentinc/ksqldb-server:0.25.1
    container_name: ksqldb-server
    depends_on:
      - broker
    ports:
      - "8088:8088"
    environment:
      KSQL_LISTENERS: http://0.0.0.0:8088
      KSQL_BOOTSTRAP_SERVERS: broker:9092
      KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE: "true"
      KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE: "true"
```
